
server:
  port: 9411

spring:
  application:
    name: jplat-zipkin-server
  data:
    mongodb:
      uri: mongodb://http://192.168.213.130:27017
      database: ziplin #表示当前程序不使用sleuth
  #rabbitmq:
    #host: 192.168.213.130
    #port: 5672
    #username: rabbit
    #password: 123456
  sleuth:
    sampler:
      percentage: 1.0
    enabled: false


zipkin:
  #storage:
    #type: elasticsearch
    #StorageComponent: elasticsearch
    #elasticsearch:
      #cluster: elasticsearch
      #hosts: 192.168.0.102:9200
      #max-requests: 64
      #index: zipkin
      #index-shards: 5
      #index-replicas: 1

  collector:
    rabbitmq:
      #uri: amqp://rabbit:123456@192.168.213.130:5672
      uri: amqp://rabbit:123456@192.168.0.102:5672
      queue: zipkin


eureka:
  client:
    service-url:
      defaultZone: http://localhost:28080/eureka/

