
server:
  port: 9411

spring:
  application:
    name: jplat-zipkin-server
  data:
    mongodb:
      uri: mongodb://http://192.168.213.130:27017
      database: ziplin #表示当前程序不使用sleuth
  rabbitmq:
    host: 192.168.213.130
    port: 5672
    username: rabbit
    password: 123456
  sleuth:
    sampler:
      percentage: 1
    enabled: false


#zipkin:
  #collector:
    #rabbitmq:
      #uri: amqp://rabbit:123456@192.168.213.130:5672
      #queue: zipkin


eureka:
  client:
    service-url:
      defaultZone: http://localhost:28080/eureka/

